#!/usr/bin/env python
"""Print the constants in turboctl.global_constants.py in a shell-compatible
format.

This is a Python script intended to be used in a shell-scripting environment
and therefore uses the same conventions as other shell scripts in TurboCtl
(no file ending, shebang at the start, output by printing etc.).

Use `eval $(./global-constants)` to load the constants as shell variables.
(Using eval shouldn't cause any extra danger by loading "dirty" data here;
global_constants.py is a Python file that can execute arbitrary code upon
import so there's no point in trying to sanitize its data.
"""
from turboctl import global_constants


attributes = dir(global_constants)
constants = [s for s in attributes if s[0] != '_' and s.isupper()]
for name in constants:
    value = getattr(global_constants, name)
    print(f"{name}='{value}'")
