#!/usr/bin/env bash
# Compile the TurboCtl documentation.

# Load $SPHINX_PATH.
SPHINX_PATH="$(python -c 'from turboctl.global_constants import SPHINX_PATH; print(SPHINX_PATH)')"

# Compile docs in $SPHINX_PATH.
cd $SPHINX_PATH
make html
